baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'luana'
theme = 'blueberry'

[menu]
    [[menu.main]]
    name = 'home'
    url = '/'

    [[menu.main]]
    name = 'posts'
    url = '/posts/'

    [[menu.main]]
    name = 'tags'
    url = '/tags/'
